### ISSUE TITLE
Can't install on Ledger Nano X on MacOS

### ISSUE THREAD

**Issue by kwunyeung** [iov-one/ledger-iov#28]
The target ID for nano X has to be 0x33000004 for Ledger Nano X according to 

https://github.com/LedgerHQ/blue-loader-python/issues/58

but unfortunately the ledgerblue module doesn't work with Nano X for now. I get the same errors as in that issue.

**Comment by webmaster128** [comment]
Thanks @kwunyeung for raising this issue. Please note that there is no official support for the Ledger Nano X yet, so we expect this to fail at many points even if the code should be ready for future Ledger Nano X support. For this reason the mid term fix is to improve documentation and remove the X from the README.

**Comment by justinvforvendetta** [comment]
@kwunyeung many of us have brought this up. we have no way of testing our apps that work on S with the nano X.

**Comment by jleni** [comment]
The SDK is for Ledger Nano X is not public. The code and UI are not identical so without the SDK you cannot compile it and the binaries for Nano S are not compatible with Nano X binaries. 
While it is tested and working, it will only be available to users one Ledger publishes in the App Catalog in Ledger Live.
